name: collins-paper
version: 1.4
main: org.sawiq.collins.paper.CollinsPaperPlugin
api-version: "1.21"
folia-supported: true
authors: [sawiq_, Zorsh, EssciZ]
website: https://discord.gg/jsH9bGj2NU

commands:
  collins:
    description: Collins screens manager
    usage: /collins <pos1|pos2|create|seturl|play|stop|pause|resume|loop|quality|seek|back|volume|radius|remove|list|playlist>
    aliases: [col]

permissions:
  collins.admin:
    default: op
